### ISSUE TITLE
CLTools Wizard: Reorder Input / Output Ports

### ISSUE THREAD

**Issue by khoegenauer** [VisTrails/VisTrails#1023]
Platform: Ubuntu 14.04 64-bit
VT Version: v2.1.5.9a01936a5640

Steps to recreate:
Create multiple Input Ports (Input1, Input2, Input3) and one Output Port (Output1).
Change Output1 to String, make visible, and generate a string for the description field.
Highlight Output1 (Bring into focus), and click the "up arrow" to move Output1 up the stack.

Results:
After one click, Output1 is moved up one spot in the stack, as expected, leaving Input3 on the bottom. However, the focus stays on Input3, which is now set to visible, type set to string, with it's description field overwritten by the contents from the description field of Output1.
Clicking the up arrow again, moves Input3 (which continues to retain the focus).

**Comment by remram44** [comment]
Thanks for the report!

There is indeed a problem, only happens for the "options" (so: prefix, flag, and description).

Fixed on v2.1 with bec1f386:
```diff
--- a/vistrails/packages/CLTools/wizard.py
+++ b/vistrails/packages/CLTools/wizard.py
@@ -1013,8 +1013,8 @@ class QArgWidget(QtGui.QWidget):
     def toList(self):
         self.getValues()
         if self.argtype not in self.stdTypes:
-            return [self.argtype, self.name, self.klass, self.options]
+            return [self.argtype, self.name, self.klass, dict(self.options)]
         else:
-            return [self.name, self.klass, self.options]
+            return [self.name, self.klass, dict(self.options)]
 
     def fromList(self, arg):
```
