### ISSUE TITLE
Custom VTK hasher

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1056]
Is the [custom `vtk_hasher()`](https://github.com/VisTrails/VisTrails/blob/a416082c56b812881048149c34dedb1fa660ab39/vistrails/packages/vtk/hasher.py#L43) still useful? What for?

Also, tracing it seems to get modules with negative ids, I don't know where those come from.

**Comment by dakoop** [comment]
Yes. The custom hasher is there to make sure that if additional output connections are added to a module, those outputs are computed. We don't want to compute all outputs if they aren't used, and we also don't want to call each output more than once. Thus, the getters are called for the outputs at the **end** of the compute method. This means we need to recompute when a new output connection is added to a module.

I believe the negative ids come from the persistent pipeline that lives in the cached interpreter.
