### ISSUE TITLE
runvistrails.py on Windows binaries

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1061]
Although the Windows binaries still come with the runvistrails.py script, it is not run when starting vistrails (vistrail/run.py is started directly). This means that PATH is not set, causing VisTrails to call the system's pip.exe if present (never the bundled one).

Additionally, the bundled pip.exe doesn't start (exits without any message, and status -1).

There was also a typo in runvistrails.py, fixed by 58a08e6d.

**Comment by remram44** [comment]
@rexissimus:
> Should we add tej to 2.2 branch? The builder has no way to add vistrails packages.

I don't know why we can't install tej the "normal" way (setuptools), but it can be copied to vistrails/packages/ without change. That probably makes sense, since it would be the only package loaded through pkg_resources.

**Comment by rexissimus** [comment]
Commit f1981d71b99de25961d610937e3c764c69ba34b5 calls runvistrails.py when starting on windows normally. I had to use some relative paths, otherwise the string is too long, but this seems to work. But it needs more testing.

**Comment by remram44** [comment]
It seems that it still runs `run.py` ([pic](http://i.imgur.com/XzpWSBS.png))

Also, I added vistrails-tej as requested, so it needs tej. tdparser is also missing.

**Comment by remram44** [comment]
It looks like you fixed one of three locations:
* There's the "start menu" shortcut,
* a desktop shortcut (which you fixed),
* and the file association, through a registry key

I'll see if I can fix these myself since you already made the change for one of them.

**Comment by remram44** [comment]
Alright I went further and removed runvistrails's arguments, because I tend to hit the size limit Windows sets on shortcuts.

**Comment by remram44** [comment]
Ok, so pip & other executables in Python27_64\Scripts\ cannot be run because the *-script.py files have a shebang like `#!c:\Python27_64_VTK6\python.exe`. They work if you replace that with `#!python.exe`. This is because of the magic that goes into the .exe wrappers used by setuptools.

**Comment by remram44** [comment]
Interestingly, if said wrapper fails to execute Python, it displays "failed to create process" and still returns 0, which makes our py_import machinery display `PyImportBug: Installation of package 'tej' succeeded, but import still fails.`.

**Comment by remram44** [comment]
I made the change, rebuilding now; we should probably have a script to make `Scripts\*` relocatable.

Hopefully everything works and we can release the binaries!

**Comment by rexissimus** [comment]
Looks good!
* On Windows, PIP is now working through pip.exe (if running as admin).
* tej is now included on Mac and Windows.
* SQLAlchemy is included on Mac and Windows.
* sklearn is also included (scipy and numpy is updated).

The preliminary binaries should be available here shortly:
http://128.238.102.101:9050/vistrails_2.2_4f4ee6fa379a/

**Comment by remram44** [comment]
It looks like the Mac binary comes with the postgresql connector, while the Windows binaries don't. I'm not sure whether it's worth fixing.

**Comment by rexissimus** [comment]
I don't think it is important, unless we have a policy which connectors the sql package should support?

**Comment by remram44** [comment]
We don't really; SQLAlchemy supports a lot more protocols like mssql and oracle. Should we tag and release?

**Comment by rexissimus** [comment]
Yes, I can do the release on Monday.
