### ISSUE TITLE
Hidden workspace entry for imported pipeline

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1062]
Importing a single pipeline doesn't show an entry in the workspace dialog, making it impossible to select it.

Bisected to d0dc3525, cc @rexissimus

**Comment by remram44** [comment]
Now importing a workflow doesn't close the first empty untitled vistrail, like the "open" function does.

Should this logic really be duplicated everywhere this way? It is obviously error-prone.

**Comment by rexissimus** [comment]
Ideally `add_vt_window` should go into `create_view`. But for some reason (that I don't remember) this caused problems. This code is brittle and I did not want do do too many changes.

Fixed the first vistrail in b29fb763f234f4a9eb58ef18da6a7f23f3f6daaf.
