### ISSUE TITLE
ALPS on VisTrails 2.2

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1070]
~~Subworkflows need to be opened, upgraded and saved back, no automatic upgrade happens~~

ALPS setup discussion is here, will open a separate ticket for clarity :wink:

Follows up on #1067

**Comment by vistrails-dev** [comment]
I know, and tried it. Unfortunately bumping the version number makes the package initialization fail, and I thus cannot open them. I’ll try to edit them manually.

Matthias

**Comment by remram44** [comment]
I should have done all the necessary changes on ALPS in our [`alps-mpl`](https://github.com/VisTrails/VisTrails/compare/v2.2...alps-mpl) branch (I imported ALPS from your SVN server). Is there something I forgot?

**Comment by vistrails-dev** [comment]
I needed the open and save the ShowMplPlot.xml file and everything worked as long as I left the version number at 2.2.0.

I now bumped the version number of ALPS from 2.2.0 to 2.2.1 and get this error even if I comment out the subworkflows:

Critical message:

Error changing version

 
InvalidPipeline: Pipeline has errors. Please see the detailed message for more information.
Missing version 2.2.0 of package org.comp-phys.alps
Upgrading workflow failed.
Output port "self" of module "MplXYPlot" exists, but signatures differ "(org.vistrails.vistrails.basic:Module)" != "(org.vistrails.vistrails.matplotlib:MplPlot)"
 
 
Time:
2015-04-30 21:26:09,015
Location:
/Applications/VisTrails/VisTrails.app/Contents/Resources/lib/python2.7/vistrails/gui/vistrail_controller.py, line 564

**Comment by remram44** [comment]
Yes, MplXYPlot now uses the "value" output port. An upgrade is necessary for the rename, which I provided on branch `alps-mpl` (50e2c1bf).

**Comment by vistrails-dev** [comment]
It does not seem to work though, even using that.

Matthias

**Comment by vistrails-dev** [comment]
Just to clarify: the problem happens when I bump the ALPS version number from 2.2.0 to 2.2.1

**Comment by remram44** [comment]
I see. From the log you posted, it looks like it doesn't upgrade to 2.2.1; did you change the target version numbers from 2.2.0 from 2.2.1 in `handle_module_upgrade_request()`, in `init.py`?

**Comment by vistrails-dev** [comment]
Thank you, that helped!

**Comment by vistrails-dev** [comment]
ALPS now seems to work well on my Mac, and the latest package that works is uploaded to our server. I’ll start on the Windows builds now.

Matthias

**Comment by vistrails-dev** [comment]
The Win32 version also works but is not yet on the server. I’m struggling with memory corruption caused by Boost.Python on Win64. Knowing which compiler Python was built with might help resolve the issue.

Matthias
