### ISSUE TITLE
Executable documents are broken

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#1086]
The latex embedding was not using the new parameters.

It also looks like the generation of the images are not working.

**Comment by remram44** [comment]
Should definitely be covered by tests

**Comment by rexissimus** [comment]
Yes. But I think we would need latex set up on the build machine, a platform-specific latex file, call a new instance of vistrails (since test suite is not single instance?), and somehow test if the images is really included (for me it succeeds with empty figures). Maybe it is better to add it to the post-build checklist?

There is also a crowdlabs-version that does not execute locally (which I think is the preferred way to use executable documents), but then the image generation is not tested.

**Comment by remram44** [comment]
Solutions are:
* Have runtestsuite.py start a new VisTrails (shouldn't really interfere, the singleinstance code shouldn't trigger here)
* Have a test script separate from runtestsuite.py

On another note, I think batch mode shouldn't use singleinstance, ever.
