### ISSUE TITLE
current_version and reusing existing upgrades are broken

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#1095]
* Upgrading an out-of-date workflow creates a new version, but current_version still refers to the old version. This breaks the use of current_version to map the current pipeline to workflow executions (used by PROV exporter #1075 #1076).
* Switching to a different version node and back always creates a new upgrade version. The existing upgrade is not used!

This may be related to hide-upgrades #1046

**Comment by remram44** [comment]
The intention was for `current_version` to still point to the actual (e.g. upgraded) version. In fact, I added `current_base_version` for the original (parent of the chain of upgrades).

**Comment by remram44** [comment]
Looks somewhat related to #1052

**Comment by rexissimus** [comment]
As @remram44 noted, this looks like an issue when we have `unflushed` upgrades. We cannot rely on `current_version` pointing to the same pipeline as `current_pipeline`. If we need a specific pipeline version we need to construct the pipeline from the vistrail (or flush the upgrade, but we may not want that). This is probably only relevant in a few cases, such as the provenance export.
