### ISSUE TITLE
Moving mouse causes flicker in pipeline view

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#1096]
I only see this on Mac. Is the pipeline being redrawn when the mouse is moved? Do anyone else see this?

**Comment by remram44** [comment]
Do you still see this @rexissimus? I think @dakoop mentioned he didn't see it either...

**Comment by rexissimus** [comment]
This only happens while mirroring the desktop through TeamViewer. The view is not being updated and I do not see any additional events fired. It looks like TeamViewer is causing a redraw of the graphics view. The flickering is minor so I am closing this.
