### ISSUE TITLE
Exception when adding a cycle in a pipeline

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1097]
This is because of `mark_list_depth()`; previously there was no problem with introducing cycles in a workflow (you just got an error when trying to run it, from the signature computation step: `vistrails.core.vistrail.pipeline.CycleInPipeline`).

![working](https://cloud.githubusercontent.com/assets/426784/8319355/c7066ce4-19c2-11e5-87c3-67ccc01e2dea.png)

Now it makes the GUI unusable.

![broken](https://cloud.githubusercontent.com/assets/426784/8319357/ca291d40-19c2-11e5-94b1-8b18dd520385.png)

**Comment by remram44** [comment]
#1098 fixes the UI, but I think `mark_list_depth()` should be fixed anyway. Is it just for the UI, or is it what's used by the interpreter as well?

**Comment by rexissimus** [comment]
`mark_list_depth` is only used by the UI, and should only be called when we have a valid pipeline. If #1098 makes sure pipelines with cycles are correctly marked as invalid, this should be enough.
