### ISSUE TITLE
Function-only port

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1099]
There should be a way to set ports to only accept functions and not connections. This would be used for things that are needed early in the execution (like the hashing step): in the persistent_archive package, for the relative_to port on File (#1057)

(see also #973?)

**Comment by rexissimus** [comment]
Control Parameters works like this. But they are supposed to modify the behaviour of the module more than normal parameters, so I am not sure `relative_to` is a good fit for this. They are also not visible as normal parameters, but can be used in module configuration interfaces.

**Comment by remram44** [comment]
The fact that they don't appear in the port list is a problem...

I've worked around this in #1057 (by falling back on a "hash of everything" if you're not using functions, but you usually are; I might want to print a warning though)
