### ISSUE TITLE
Some Users Guide Examples are not working

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#1107]
There seems to be several issues with the linked examples in the users guide (Tested in single instance mode)
- [x] [cfassistant2.vtl](www.vistrails.org/usersguide/v2.2/examples/cfassistant2.vtl) - Unexpected Exception during upgrade
- [x] [global_variables1.vtl](www.vistrails.org/usersguide/v2.2/examples/global_variables_1.vtl) - Error upgrading vtkDataSetReader (same for [vtk_http.vtl](www.vistrails.org/usersguide/v2.2/examples/vtk_http.vtl))
- [x] [mashups1.vtl](www.vistrails.org/usersguide/v2.2/examples/mashups1.vtl) - Error: `Cannot translate old mashup through upgrade`
- [x] [pe1.vtl](www.vistrails.org/usersguide/v2.2/examples/pe1.vtl) - Parameter Exploration is missing parameters (same for pe2, pe3, pe4)

**Comment by remram44** [comment]
These should really be covered by the test suite, one way or another.

**Comment by rexissimus** [comment]
Yes. We could probably test loading all the vtl files and check for errors.

**Comment by rexissimus** [comment]
Added test with commit 4f7cdb3ae11e23b0be210bc6103cf13803ff571e. The test only runs the specified pipelines and would not have detected all of these issues, so it is still necessary to manually check the examples occasionally.

**Comment by remram44** [comment]
You mean it would have missed the parameter explorations and mashups? Or other things as well.

**Comment by remram44** [comment]
Interestingly your test doesn't pass on buildbot.

**Comment by rexissimus** [comment]
It looks like `suds` was not installed on the Debian machine. It seems to work now. Although there is an error in the log that need fixing: `'DBVistrail' object has no attribute 'get_used_packages'`

**Comment by rexissimus** [comment]
Reverting the test until I can figure this out.

**Comment by rexissimus** [comment]
#1111 should fix this
