### ISSUE TITLE
Close workflows with [Ctrl]+[W] or [Alt]+[f], [c] on windows

### ISSUE THREAD

**Issue by daren-thomas** [VisTrails/VisTrails#1108]
This is a really small one that still tends to bug me: [Ctrl]+[F4] is the only way to close a workflow with the keyboard. And with the mouse, you need to go into the File menu and choose close - as opposed to right-click on the current vistrail and chose "close" from the (already implemented) context menu. The context menu only has a "Open in New Window" menu item. Why not add a "Close"?

**Comment by rexissimus** [comment]
You can also use [Delete] on a vistrail in the workspace. But I agree that the context menu should have a "close" option for consistency.

**Comment by daren-thomas** [comment]
great! that solves my gripe!

**Comment by remram44** [comment]
Added with 8a0610da.
