### ISSUE TITLE
"Check now" button in job monitor doesn't appear to work

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1119]
Might be a bug in tej, but I think this is the monitor. Re-running the workflow works (and updates the status in the monitor).

**Comment by rexissimus** [comment]
I cannot reproduce this. Can you provide an example?

**Comment by remram44** [comment]
On `tej-docs` (#1105) there is `examples/tej-primes.vt` which shows the problem (you will need to point the Queue module on an actual SSH server). I'll look into it again.

**Comment by rexissimus** [comment]
Now I see what you mean. The workflow is not being marked as finished. This was because of a bug with the new ready state. This should be fixed by commit ca432693502f548fdd470d51fb4c456b96d46fff?

**Comment by remram44** [comment]
Yes, works!

Is it possible maybe to not have the job monitor pop up when executing a workflow with a finished job in it? Looks like it always gets shown, even if the job module is done and cached.

**Comment by rexissimus** [comment]
Commit 75d4b7a4f35d238dec5af19899ccf06d99e396d2 now stops job minitor from popping up if nothing has changed.

**Comment by remram44** [comment]
Alright, closing this!
