### ISSUE TITLE
tej can be annoying to use because of known_hosts issues

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1124]
Paramiko checks that the host you connect to is in known_hosts, same as SSH does. It will be there if you connected to it with SSH previously.

Problem is, Paramiko doesn't support all the key exchange protocols that OpenSSH does, so the entry in `known_hosts` might be for a different type of key (ECDSA, not RSA). Then paramiko (and thus tej) will refuse to connect.

This is not our bug, but users might still run into it. There should be an explanatory message somewhere that indicates how to add the correct entry to `known_hosts`.

Might be worth fixing somewhere in [tej](https://github.com/VisTrails/VisTrails/issues/1123), I'm not sure.

**Comment by rexissimus** [comment]
265ab4e7a1d89b606e4deff2b36c6d4321e7ecb3 Adds ssh key section to tej documentation.
