### ISSUE TITLE
Querying doesn't work

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1149]
Both the text query and the query by example don't appear to work.

**Comment by rexissimus** [comment]
Searching for version tags in non-upgraded workflows works. But nothing else works.

**Comment by rexissimus** [comment]
#1161 should now fix most issues.

**Comment by remram44** [comment]
It seems that searching in a workflow doesn't highlight matched modules (I'm not sure if it ever did).

**Comment by rexissimus** [comment]
What query are you using? You need to use the ``module:`` prefix to search module names.

**Comment by rexissimus** [comment]
Ok, I see the problems with the workflow search.

**Comment by rexissimus** [comment]
You are right. The workflow search view never highlighted matching modules.

227a3d3d0ac47bf319587e92fcb6a3a98b69e5ec implements matchModule for string queries.

You can now search for module names using substring or regex matching, and see the matching modules highlighted.
