### ISSUE TITLE
Waiting for job dialog doesn't allow re-checking

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1153]
I'm not sure how often the job is checked while the dialog is displayed but it appears to be very slow. The only way to force a recheck is to click cancel there, bring up the "running jobs" window, and click "check" there.

Maybe the interval should be shorter while the dialog is displayed, or there could be a "recheck" button on it?

**Comment by rexissimus** [comment]
It uses the interval set in the "running jobs" window. We could have faster timer when waiting for the job, but it would be bad to bombard the server with status requests. A "recheck" button is probably the best solution.

**Comment by remram44** [comment]
Perfect, thanks!
