### ISSUE TITLE
emacs version 24 breaks db schema generation

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#1173]
``vistrails/db/bin/generate.py`` uses emacs to indent multi-line function arguments. This works in emacs 23, but breaks in emacs 24, probably due to [this](https://bugs.launchpad.net/python-mode/+bug/1426903) issue.

The workaround is currently to install emacs 23 before generating the schema.

Can we get rid of the emacs dependency? Perhaps using something like [autopep8](https://pypi.python.org/pypi/autopep8)?

**Comment by remram44** [comment]
Should `autopep8` be added to `requirements.txt`?

**Comment by rexissimus** [comment]
No, this is only for generating the schema. It is not needed for normal use.

**Comment by remram44** [comment]
The requirements already list `Mako`, `unittest2` and `nose` which are not necessary for normal use. I'll split this into `requirements.txt` and `dev-requirements.txt`.

**Comment by rexissimus** [comment]
I think at least ``unittest2`` shoud be in ``requirements.txt``. It is used to test the binary builds.

``mako``/``docutils``/``sphinx`` may be used by package developers, but this is not essential. They may also be  used at runtime to generate dynamic packages, but we discourage that, so it may be good to leave this out.

``nose`` does not seem to be used anywhere, but it was added for ``scikit-learn`` so maybe it is needed there?
