### ISSUE TITLE
Toolbar icon display issues

### ISSUE THREAD

**Issue by dakoop** [VisTrails/VisTrails#1180]
<img width="979" alt="screen shot 2016-07-01 at 2 26 54 pm" src="https://cloud.githubusercontent.com/assets/2249780/16530864/0a0e38e0-3f98-11e6-8e05-3c9af9bf772f.png">

- master branch
- Running through conda's python interpreter
- Retina iMac
- Mac OS X 10.11.5

**Comment by remram44** [comment]
Indeed some of these icons have different sizes, I'm on it.

**Comment by remram44** [comment]
Fixed by 12609a38.

I will check if some other icons are unused.
