### ISSUE TITLE
.vt files are not being compressed

### ISSUE THREAD

**Issue by dakoop** [VisTrails/VisTrails#1182]
It seems that .vt files are not compressed after the change in #862. `zipfile` does not compress by default (https://docs.python.org/2/library/zipfile.html); `zipfile.ZIP_DEFLATED` needs to be set on the zipfile.ZipFile when created. This requires zlib, but I don't think that should be an issue on any platform.

**Comment by remram44** [comment]
Fixed by 8a138a82. Indeed, I had assumed that Python compressed ZIPs by default.
