### ISSUE TITLE
mta-yankees.vt Gmaps examples broken on win64

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#1183]
On windows, the spreadsheet cell is just white, but "open in browser" works.
Works on Linux, what about OS X?
Could there be something missing in the windows binary?

Reported on vistrails-users

**Comment by remram44** [comment]
73ca916a seems to help on Mac. Not completely sure what is going on, it seems different browsers handle this differently (and Qt is not super up to date on this).

**Comment by remram44** [comment]
73ca916a seems to help on Mac. Not completely sure what is going on, it seems different browsers handle this differently (and Qt is not super up to date on this).

Can you confirm what it does to other platforms?

**Comment by rexissimus** [comment]
:+1: It works on Windows, and still works on Linux.
