### ISSUE TITLE
PackageDir doesn't work

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1208]
It seems that the PackageDirectory option was only half migrated, changed to PackageDir everywhere except in the actual package manager code.

Also that directory gets inserted in sys.path but vistrails.packages still gets imported. Because of the way Python imports work (and the `__path__` feature), this will still not import from that directory.

**Comment by remram44** [comment]
There seem to be more problems with paths, most of them have defaults that are actually relative to `.vistrails`, but the code doesn't assume that.

**Comment by remram44** [comment]
The `dataDir` and `fileDir` options are also useless, because `core.system` doesn't actually use those (only maintains variables `__dataDir` and `__fileDir`. The `fileDir` option gets updated, but never read; `dataDir` is never touched)

I would change `core.system` to use the configuration, but that would break at startup. Or should we just remove `dataDir` and `fileDir` from configuration?

**Comment by dakoop** [comment]
Where are the underscore variables used? If they are not important, I would vote to eliminate them.

Why would it break if you change `core.system`?

**Comment by remram44** [comment]
I am referring to the [variables in `system/__init__.py`](https://github.com/VisTrails/VisTrails/blob/5b23e4347affad21ac1d5581dd282b4feef704b1/vistrails/core/system/__init__.py#L244)

`core.system` is used before the configuration is set up, so relying on the configuration there is probably not right.

`dataDir` and `fileDir` are only keeping track of the last place files where opened from/saved to, so there is not a lot of value in having them persist anyway.

**Comment by dakoop** [comment]
Do they have to be used before the config is set up, or could the ordering be changed?

Otherwise, I'm fine with eliminating them. In any case, they shouldn't be in the GUI preferences (not sure if they are).

**Comment by remram44** [comment]
It looks that those are probably safe to lookup in the configuration (`vistrails_root_directory()` and the like are less safe).

The help strings for those were "default vistrail directory"/"default data directory", so it's what #1209 changes them to do.
