### ISSUE TITLE
Improve VTK 6 support

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#739]
commit [changeset:f703fff4] adds supports for VTK 6.0.0 but there are still a few issues:

* "terminator.vt:Isosurface Script" does not work due to API changes (Only Fixing !SetInput caused a black window)
* Do we need to add new upgrade paths?

**Comment by remram44** [comment]
Is this fixed by #998?

**Comment by rexissimus** [comment]
Yes. We still support multiple versions of the VTK package using the same version identifier, but this also means we don't need to upgrade the workflow each time we switch between VTK5 and VTK6.
