### ISSUE TITLE
Packages that wrap libraries should not dynamically wrap on init

### ISSUE THREAD

**Issue by dakoop** [VisTrails/VisTrails#795]
I would like to see packages that wrap existing libraries (e.g. vtk, !JobSubmission) to **not** dynamically create wrappers on startup.  Rather, I believe they should adopt a strategy more like the new matplotlib package where the wrappers are created dynamically by a script, but the wrapper itself is static.  This way, a version number can actually mean something and interfaces can be assumed cross-platform.  It also makes debugging individual packages a bit easier.  Finally, UV-CDAT users have commented on the long startup time for the VTK package which is partially caused by this wrapping running each time on startup.  Note that the wrapper script could be run in a single step to update !VisTrails bindings so this shouldn't be a big deal for developers or users wishing to extend both the underlying library and !VisTrails wrapping.

**Comment by remram44** [comment]
Superseded by #991.
