### ISSUE TITLE
Map and suspended jobs

### ISSUE THREAD

**Issue by dakoop** [VisTrails/VisTrails#810]
I have a situation where I have a Module that generates an external job that runs and raises ModuleSuspended.  The external job eventually writes a string to a specific file in a run-specific directory that can be checked to determine if the job is done and whether it completed successfully.  Now, I would like to run that Module as part of a Map where I test different tolerances.  The original code was written to create "_#" style directories for each run (e.g abc_1, abc_2, ...), but when coming back after the jobs complete, the suspended module is gone and I have no way to determine which module corresponds to which directory.  So I decided I could use the signature for the upstream subworkflow of the Module in the directory names--a quick version of the persistent file (e.g. abc_78cdc3e).  However, it seems that Map's updateFunctionPort doesn't recompute the signatures each time through which I assume also means individual executions of the loop are also not cached (e.g. if I run with tolerance = `[1,2,3]` and then `[2,3,4]`, it would have to execute all three each time instead of just doing 4 the second time).  It also means the signature is the same each time through the loop which means the directory name is not unique.

I can probably compute a better signature myself in the module, but I wonder if
1. there is a better idea for this, or
2. if the controlflow modules should compute signatures correctly before being put into the interpreter (e.g. updateFunctionPort updates signatures).

This affects v2.1 and master.

**Comment by remram44** [comment]
This might have been fixed by the [jobs-use-signatures](https://github.com/VisTrails/VisTrails/commit/3f1fde880d862a02d01a9238ed828323a361d6ae) branch.

**Comment by rexissimus** [comment]
Yes, jobs now use module signature as identifier, and signatures works when using Map.
