### ISSUE TITLE
Tuple upgrades broken

### ISSUE THREAD

**Issue by dakoop** [VisTrails/VisTrails#856]
I opened an old vistrail with older Tuple modules and the upgrade seems to be broken in both v2.1 and master.  I see a message:

```
InvalidPipeline: Pipeline has errors. Please see the detailed message for more information.
  Missing version 1.6 of package edu.utah.sci.vistrails.basic
  Upgrading workflow failed.
  Output port "self" of module "Tuple" exists, but signatures differ "(org.vistrails.vistrails.basic:Module)" != "(org.vistrails.vistrails.basic:Tuple)"
```

I'm looking into this, but I believe it will be an easy fix (just adding the override for 'self' -> 'self').

**Comment by remram44** [comment]
Using the old `Tuple`-typed ports is very broken; the "tuple" input port of `Untuple` doesn't exist anymore.

It seems that I removed it with ad39a00c, (pre-v2.1.0) but no upgrade path is provided.

**Comment by remram44** [comment]
I think my reasoning at the time is that the `Tuple` type should not be used, the correct way is to connect the `value` port, which has an actual tuple type (like `(basic:String, basic:Integer)`). There is no way to upgrade in the general case. Should this be added back? (it's been out for a while)

**Comment by dakoop** [comment]
Yes, that was the decision, but I thought that we believed that any use of the actual `self` port would still be ok (port is just typed as `Module` instead of `Tuple`) and there shouldn't be many times that `self` was used. However, the change to not pass modules along connections may impact this. Do we have examples/packages that are broken?

**Comment by remram44** [comment]
Passing modules on connections only warns. Using `Tuple`'s `self` port still works, but `Untuple` doesn't have a matching input port.

**Comment by dakoop** [comment]
Right. Do we have examples of `Untuple` being used with a `Tuple` as input?

**Comment by remram44** [comment]
I tested all the examples that have Tuple or Untuple modules. I found two new bugs, but no workflow that wouldn't execute.
