### ISSUE TITLE
URL package only caches HTTP(s) files

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#858]
I just merged `new-url-package` which adds support for FTP and SSH file downloads.

The problem is, only HTTP(s) files get cached on disk, other URLs will be downloaded every session (the DownloadFile module is cacheable, so won't reexecute every time).

There might be ways of getting a timestamp from the server for both SSH and FTP which would allow us to cache.

**Comment by remram44** [comment]
Can't think of a good solution.

**Comment by dakoop** [comment]
It doesn't look like there is a general solution for FTP--perhaps some limited support for a [MD5 command](http://www.faqs.org/rfcs/ftp-rfcs.html). For SSH, if you have shell access, you could try some commands (e.g. stat) but this probably is also not general.
