### ISSUE TITLE
Package configuration editor is broken

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#904]
Specifically:
* Unset parameters are not shown
* Restore Defaults does not work

To reproduce: Load CLTools and open configuration editor. The env parameter should be visible and Restore Defaults throws an exception.

**Comment by remram44** [comment]
Should I remove the `# FIXME Need to fix this`? @dakoop do you know what it's about?

**Comment by dakoop** [comment]
There seems to still be an issue where setting preferences in the normal, more user-friendly panels does not update the advanced panel (and vice versa).

**Comment by remram44** [comment]
Filed as #995
