### ISSUE TITLE
Mac binary scripts/ contain temp files

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#910]
There are `*~` files in several releases. Is something wrong with a release script? Should they clean the tree?

**Comment by remram44** [comment]
I think these were fixed, and with #951 we can build from clean trees on buildbot.

Not sure about the scripts situation at this point.

**Comment by rexissimus** [comment]
Yes, the scripts have been improved, manual builds could possibly still include temp files, but buildbot should always generate clean builds.
