### ISSUE TITLE
Package configuration is broken

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#986]
Boolean options still work but others are missing from both the startup XML and the configuration dialog.

Bisected to branch `rewrite-startup` (cebe088e, 1c9bb479 or cfb7f2e7).

ImageMagick:

![imagemagick code](http://i.imgur.com/j3Wo2iW.png)

![imagemagick conf](http://i.imgur.com/zQGiLPm.png)

RemoteQ:

![remoteq code](http://i.imgur.com/Gw2u1iu.png)

![remoteq conf](http://i.imgur.com/hmsLyxb.png)

**Comment by rexissimus** [comment]
Also see #904

**Comment by remram44** [comment]
One more screenshot:

![](http://i.imgur.com/9x6dMIw.png)
