### ISSUE TITLE
VisTrails console doesn't seem to work anymore

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#988]
![VisTrails console](http://i.imgur.com/sC5S0q3.png)

Do you see this as well? Is this from an IPython or pygments upgrade?

**Comment by rexissimus** [comment]
I don't see this on Mac. I updated pygments and then IPython and it still works.

**Comment by remram44** [comment]
I realize I didn't describe what I did: I'm typing "import " and immediately see this traceback.

**Comment by rexissimus** [comment]
Ok, I see that now.

**Comment by rexissimus** [comment]
This is an ipython/pygments compatibility issue:
https://github.com/ipython/ipython/issues/6986

It will hopefully be fixed in IPython 2.4. Meanwhile, downgrading pygments should fix it:

    pip uninstall pygments && pip install pygments==1.6

**Comment by remram44** [comment]
Good find! Not much we can do here but wait -- IPython folks say 2.4 will be released along with 3.0, to support the new notebook format.
